name: Noisescape Build CD

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: "10.0.x"

    - name: Set up Node.JS
      uses: actions/setup-node@v7
      with:
        node-version: "24"
        cache: "npm"
        cache-dependency-path: "./client/package-lock.json"

    - name: Install Velopack CLI
      run: dotnet tool install -g vpk

    - name: Install client dependencies
      working-directory: ./client
      run: npm ci

    - name: Run client build command
      working-directory: ./client
      run: npm run build

    - name: Restore C# dependencies
      working-directory: ./src
      run: dotnet restore -r win-x64

    - name: Build and publish C# application binary
      working-directory: ./src
      run: dotnet publish Noisescape.csproj --no-restore -c Release --self-contained -r win-x64 -o ../publish

    - name: Pack using Velopack
      run: |
        $version = "${{ github.event.release.tag_name }}".TrimStart("v")
        vpk pack --packId Ditpowuh.Noisescape --packVersion $version --packDir .\publish --mainExe Noisescape.exe --packTitle Noisescape --packAuthors Ditpowuh --icon src\Resources\wwwroot\Icon.ico

    - name: Rename packaged files
      run: |
        Move-Item "./Releases/Ditpowuh.Noisescape-win-Setup.exe" "./Releases/NoisescapeSetup.exe"
        Move-Item "./Releases/Ditpowuh.Noisescape-win-Portable.zip" "./Releases/NoisescapePortable.zip"

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          ./Releases/NoisescapeSetup.exe
          ./Releases/NoisescapePortable.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
